const watchList = [
    "19-2",
    "30 Rock",
    "A.P. Bio",
    "After Life",
    "Archer",
    "Arrested Development",
    "Atlanta",
    "Avatar",
    "Bad Education",
    "Band Of Brother",
    "Banshee",
    "Better Off Ted",
    "Blue Mountain State",
    "Bored To Death",
    "Champagne ILL",
    "Community",
    "Crashing",
    "Cuckoo",
    "Dark",
    "Derry Girls",
    "Detroiters",
    "Dirk Gently Holistic Detective Agency",
    "Firefly",
    "Flight Of The Concords",
    "Frasier",
    "Generation Kill",
    "Happy Endings",
    "How To Make It In America",
    "How To With John Wilson",
    "I Think You Should Leave",
    "It's Always Sunny In Philidelphia",
    "Jonathan Strange & Mr Norrel",
    "Kevin Can F**k Himself",
    "Kingdom",
    "Malcolm In The Middle",
    "Midnight Mass",
    "Mindhunter",
    "Moonbase",
    "Mr Robot",
    "Nathan For You",
    "New Girl",
    "Nirvana The Band The Show",
    "One Punch Man",
    "Only Murders In The Building",
    "Phoneshop",
    "Rehearsal",
    "Santa Clarita Diet",
    "Schitts Creek",
    "Seinfeld",
    "Severance",
    "Silicon Valley",
    "Star Trek TNG",
    "Succession",
    "Taskmaster",
    "Ted Lasso",
    "The Expanse",
    "The Office",
    "The Resort",
    "The Witcher",
    "Travelers",
    "Veep",
    "Vice Principals",
    "Wayne",
    "You're The Worst"
]

export default watchList